// Copyright (C) 2026 Slack Technologies, LLC
// SPDX-License-Identifier: Apache-2.0
package com.slack.circuit.subcircuit

/**
 * Factory interface for creating [SubPresenter] instances for a given [SubScreen].
 *
 * Implementations are typically generated by the `@SubCircuitInject` annotation processor.
 */
public fun interface SubPresenterFactory {
  /**
   * Creates a [SubPresenter] for the given [screen].
   *
   * @param screen The screen to create a presenter for.
   * @return A [SubPresenter] if this factory can handle the given screen, null otherwise.
   */
  public fun create(screen: SubScreen<*>): SubPresenter<*, *>?
}
