// Copyright (C) 2026 Slack Technologies, LLC
// SPDX-License-Identifier: Apache-2.0
package com.slack.circuit.subcircuit

/**
 * Factory interface for creating [SubUi] instances for a given [SubScreen].
 *
 * Implementations are typically generated by the `@SubCircuitInject` annotation processor.
 */
public fun interface SubUiFactory {
  /**
   * Creates a [SubUi] for the given [screen].
   *
   * @param screen The screen to create a UI for.
   * @return A [SubUi] if this factory can handle the given screen, null otherwise.
   */
  public fun create(screen: SubScreen<*>): SubUi<*>?
}
