complexity:
  LongMethod:
    threshold: 120
  NestedBlockDepth:
    threshold: 6

coroutines:
  InjectDispatcher:
    excludes: ['**/samples/**']

naming:
  FunctionNaming:
    ignoreAnnotated:
      - 'Composable'
      - 'androidx.compose.runtime.Composable'

style:
  ReturnCount:
    max: 4
  UnusedPrivateMember:
    ignoreAnnotated:
      - 'Preview'
      - 'androidx.compose.desktop.ui.tooling.preview.Preview'
  # This rule ends up causing more style issues than not
  BracesOnWhenStatements:
    active: false
  MagicNumber:
    # Allow magic numbers in Compose previews
    ignoreAnnotated:
      - 'androidx.compose.ui.tooling.preview.Preview'
      - 'androidx.compose.desktop.ui.tooling.preview.Preview'
      - 'Preview'

empty-blocks:
  EmptyDefaultConstructor:
    excludes: ["**/build/**"]

TwitterCompose:
  ComposableNaming:
    # TODO disabled for now pending https://github.com/twitter/compose-rules/issues/104
    active: false
