name: Emulator-WTF

on:
  # Only run on my branch for testing purposes
  push:
    branches:
      - js_test_out_emulator_wtf

jobs:
  run-tests:
    runs-on: macOS-latest
    env:
      # Test on API 30 because that's the first version with ATDs
      API_LEVEL: '30'
      AVD_TARGET: 'aosp_atd'

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: 'true'

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1

      - name: Check LFS files
        uses: actionsdesk/lfs-warning@v3.2

      - name: Install JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '19'

      - name: Build APKs & run tests via Gradle task
        id: gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: check samples:star:apk:assembleRelease samples:star:assembleAndroidTest samples:star:testReleaseWithEmulatorWtf --continue --no-configuration-cache
          gradle-home-cache-cleanup: true
          cache-read-only: false

      - name: Run tests on Emulator.wtf via Github Action
        uses: emulator-wtf/run-tests@v0
        with:
          api-token: ${{ secrets.EMULATOR_WTF_TOKEN }}
          app: samples/star/apk/build/outputs/apk/release/apk-release.apk
          test: samples/star/build/outputs/apk/androidTest/release/star-release-androidTest.apk
          devices: model=NexusLowRes,version=33
          use-orchestrator: true
          clear-package-data: true
          record-video: true
          num-shards: 1
          outputs-dir: build/test-results

      - name: Publish test report
        uses: mikepenz/action-junit-report@v2
        if: always()
        with:
          report_paths: build/test-results/**/*.xml