name: SauceLabs

on:
  # Only run on my branch for testing purposes
  push:
    branches:
      - js_test_out_sauce_labs

jobs:
  run-tests:
    runs-on: macOS-latest
    env:
      # Test on API 30 because that's the first version with ATDs
      API_LEVEL: '30'
      AVD_TARGET: 'aosp_atd'

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: 'true'

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1

      - name: Check LFS files
        uses: actionsdesk/lfs-warning@v3.2

      - name: Install JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '19'

      - name: Build APKs
        id: gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: samples:star:apk:assembleRelease samples:star:assembleAndroidTest --continue --no-configuration-cache
          gradle-home-cache-cleanup: true
          cache-read-only: false

      - name: Run tests on SauceLabs
        env:
          SAUCELABS_TOKEN: ${{ secrets.SAUCELABS_TOKEN }}
        run: ./scripts/run_tests_on_saucelabs.sh

      - name: Publish test report
        uses: mikepenz/action-junit-report@v2
        if: always()
        with:
          report_paths: build/test-results/**/*.xml